### ISSUE TITLE
部署报错注入失败

### ISSUE THREAD

**Issue by q894944272** [chengchenrui/shiro-security#1]
<context:component-scan base-package="com.cheng.shiro.controller"/>
=><context:component-scan base-package="com.cheng.shiro.*"/>

**Comment by chengchenrui** [comment]
web.xml 文件里的Spring监听配置改一下
如下：
<param-value>classpath:spring/applicationContext.xml</param-value>

**Comment by chengchenrui** [comment]
@q894944272 
web.xml 文件里的Spring监听配置改一下
如下：
classpath:spring/applicationContext.xml
